-- Seeder: 002_seed_products
-- Populates initial coffee equipment and specialty coffee bean products with images and specifications

INSERT INTO `products`
  (`id`, `name`, `brand`, `description`, `price`, `stock`, `rating`, `review_count`, `origin`, `species`, `roast_level`, `tasted`, `processing`, `dimensions`, `weight`, `capacity`, `color`)
VALUES
  (
    1,
    'HARIO CAFE PRESS SLIM GREY 240ML',
    'Hario',
    'Hario Cafe Press Slim is a stylish and compact French press coffee maker, perfect for brewing 1-2 cups of rich, full-bodied coffee.',
    480000.00,
    15,
    5.0,
    7,
    'Japan',
    NULL,
    NULL,
    NULL,
    NULL,
    '11x16,5x8cm',
    '350gr',
    '240ml',
    'Abu-abu / Grey'
  ),
  (
    2,
    'ABID CLEVER DRIPPER 102',
    'UbruKopi',
    'Clever Coffee Dripper combines the best features of French press immersion brewing and pour-over drip extraction.',
    420000.00,
    20,
    4.8,
    14,
    'Taiwan',
    NULL,
    NULL,
    NULL,
    NULL,
    '13x13x14cm',
    '300gr',
    '500ml',
    'Transparan / Clear'
  ),
  (
    3,
    'FELLOW CARTER MOVE MUG 355ML',
    'Fellow',
    'Designed to amplify the senses and engineered to fit your travel needs with a snap-in splash guard and slim width.',
    580000.00,
    12,
    4.9,
    22,
    'USA',
    NULL,
    NULL,
    NULL,
    NULL,
    '7.7x7.7x15.8cm',
    '320gr',
    '355ml',
    'Matte Black'
  ),
  (
    4,
    'TIMEMORE CHESTNUT C2 MANUAL GRINDER',
    'Timemore',
    'High-grade aluminum alloy manual coffee grinder equipped with CNC stainless steel conical burrs for precise grinding.',
    650000.00,
    18,
    4.9,
    45,
    'China',
    NULL,
    NULL,
    NULL,
    NULL,
    '14.7x5.2x5.2cm',
    '430gr',
    '25gr',
    'Gunmetal Grey'
  ),
  (
    5,
    'KALITA WAVE DRIPPER 185 STAINLESS',
    'Kalita',
    'Iconic flat-bottom dripper with three extraction holes ensuring even extraction and a consistent cup profile.',
    520000.00,
    25,
    4.7,
    19,
    'Japan',
    NULL,
    NULL,
    NULL,
    NULL,
    '11.5x11.5x7.5cm',
    '160gr',
    '500ml',
    'Silver'
  ),
  (
    6,
    'ORIGAMI DRIPPER S CERAMIC PINK',
    'Origami',
    'Ceramic pour-over dripper made with Mino porcelain, designed with 20 vertical grooves for optimal brew speed.',
    495000.00,
    10,
    4.8,
    11,
    'Japan',
    NULL,
    NULL,
    NULL,
    NULL,
    '11.8x11.8x7cm',
    '200gr',
    '300ml',
    'Pastel Pink'
  ),
  (
    7,
    'AEROPRESS ORIGINAL COFFEE MAKER',
    'AeroPress',
    'Rapid full-immersion brewing method producing smooth, delicious coffee without bitterness or grit.',
    590000.00,
    30,
    5.0,
    53,
    'USA',
    NULL,
    NULL,
    NULL,
    NULL,
    '13x13x29cm',
    '370gr',
    '296ml',
    'Smoke Grey'
  ),
  (
    8,
    'ACEH GAYO NATURAL SINGLE ORIGIN 250G',
    'UbruKopi',
    'Specialty Arabica coffee beans from the highlands of Aceh Gayo processed naturally with vibrant tropical fruit sweetness.',
    125000.00,
    50,
    4.9,
    38,
    'Aceh Gayo',
    'Arabica',
    'Light Roast',
    'Fruity',
    'Natural',
    '12x8x20cm',
    '250gr',
    '250gr',
    'Cokelat / Brown'
  ),
  (
    9,
    'BALI KINTAMANI ANAEROBIC 250G',
    'UbruKopi',
    'Arabica coffee grown on the volcanic slopes of Mount Batur with distinct notes of citrus orange and subtle honey aroma.',
    135000.00,
    40,
    4.8,
    27,
    'Kintamani Bali',
    'Arabica',
    'Medium Roast',
    'Floral',
    'Honey',
    '12x8x20cm',
    '250gr',
    '250gr',
    'Cokelat / Brown'
  ),
  (
    10,
    'TORAJA SAPAN WASHED 250G',
    'UbruKopi',
    'Premium high-altitude Arabica from North Toraja delivering clean cup clarity with chocolate and herbal undertones.',
    130000.00,
    35,
    4.7,
    18,
    'Toraja',
    'Arabica',
    'Medium Roast',
    'Chocolaty',
    'Washed',
    '12x8x20cm',
    '250gr',
    '250gr',
    'Cokelat / Brown'
  ),
  (
    11,
    'MANDHELING PEABERRY DARK ROAST 250G',
    'UbruKopi',
    'Rare single peaberry round beans from Sumatra Mandheling boasting thick crema, low acidity, and deep dark chocolate notes.',
    140000.00,
    25,
    4.8,
    31,
    'Mandheling',
    'Arabica',
    'Dark Roast',
    'Nutty',
    'Wet Hulled',
    '12x8x20cm',
    '250gr',
    '250gr',
    'Cokelat / Brown'
  ),
  (
    12,
    'JAVA PREANGER HONEY PROCESS 250G',
    'UbruKopi',
    'Historic Priangan Arabica dried with sweet mucilage intact, imparting gentle brown sugar and apple acidity.',
    120000.00,
    30,
    4.6,
    16,
    'Java Preanger',
    'Arabica',
    'Medium Roast',
    'Caramel',
    'Honey',
    '12x8x20cm',
    '250gr',
    '250gr',
    'Cokelat / Brown'
  ),
  (
    13,
    'FLORES BAJAWA FULL WASHED 250G',
    'UbruKopi',
    'Sourced from Ngada plateau on Flores island, known for subtle spicy notes, floral fragrance, and milk chocolate finish.',
    128000.00,
    22,
    4.7,
    12,
    'Flores Bajawa',
    'Arabica',
    'Medium-Dark Roast',
    'Spicy',
    'Washed',
    '12x8x20cm',
    '250gr',
    '250gr',
    'Cokelat / Brown'
  ),
  (
    14,
    'SIDIKALANG ROBUSTA PREMIUM 250G',
    'UbruKopi',
    'Famous legendary Robusta from North Sumatra with bold body, intense roasted nut flavor, and lingering sweetness.',
    85000.00,
    60,
    4.8,
    42,
    'Sidikalang',
    'Robusta',
    'Dark Roast',
    'Chocolaty',
    'Natural',
    '12x8x20cm',
    '250gr',
    '250gr',
    'Cokelat / Brown'
  ),
  (
    15,
    'LAMPUNG ROBUSTA GOLD 250G',
    'UbruKopi',
    'Carefully sorted Lampung Robusta beans roasted for espresso blending, rich in dark chocolate and caramel nuances.',
    80000.00,
    55,
    4.5,
    20,
    'Lampung',
    'Robusta',
    'Medium-Dark Roast',
    'Caramel',
    'Natural',
    '12x8x20cm',
    '250gr',
    '250gr',
    'Cokelat / Brown'
  ),
  (
    16,
    'COLOMBIA HUILA SUPREMO 250G',
    'UbruKopi',
    'Imported single origin from Huila department, Colombia, celebrated for juicy red apple acidity and sweet toffee body.',
    165000.00,
    20,
    4.9,
    15,
    'Colombia',
    'Arabica',
    'Light Roast',
    'Fruity',
    'Washed',
    '12x8x20cm',
    '250gr',
    '250gr',
    'Cokelat / Brown'
  )
ON DUPLICATE KEY UPDATE
  `name`         = VALUES(`name`),
  `brand`        = VALUES(`brand`),
  `description`  = VALUES(`description`),
  `price`        = VALUES(`price`),
  `stock`        = VALUES(`stock`),
  `rating`       = VALUES(`rating`),
  `review_count` = VALUES(`review_count`),
  `origin`       = VALUES(`origin`),
  `species`      = VALUES(`species`),
  `roast_level`  = VALUES(`roast_level`),
  `tasted`       = VALUES(`tasted`),
  `processing`   = VALUES(`processing`),
  `dimensions`   = VALUES(`dimensions`),
  `weight`       = VALUES(`weight`),
  `capacity`     = VALUES(`capacity`),
  `color`        = VALUES(`color`),
  `updated_at`   = CURRENT_TIMESTAMP;

INSERT INTO `product_images`
  (`id`, `product_id`, `image_url`, `is_primary`)
VALUES
  (1, 1, '/images/products/hario-press-1.jpg', TRUE),
  (2, 1, '/images/products/hario-press-2.jpg', FALSE),
  (3, 2, '/images/products/abid-1.jpg', TRUE),
  (4, 2, '/images/products/abid-2.jpg', FALSE),
  (5, 3, '/images/products/fellow-carter-1.jpg', TRUE),
  (6, 3, '/images/products/fellow-carter-2.jpg', FALSE),
  (7, 4, '/images/products/timemore-c2-1.jpg', TRUE),
  (8, 4, '/images/products/timemore-c2-2.jpg', FALSE),
  (9, 5, '/images/products/kalita-185-1.jpg', TRUE),
  (10, 5, '/images/products/kalita-185-2.jpg', FALSE),
  (11, 6, '/images/products/origami-s-1.jpg', TRUE),
  (12, 6, '/images/products/origami-s-2.jpg', FALSE),
  (13, 7, '/images/products/aeropress-1.jpg', TRUE),
  (14, 7, '/images/products/aeropress-2.jpg', FALSE),
  (15, 8, '/images/products/beans-gayo-1.jpg', TRUE),
  (16, 8, '/images/products/beans-gayo-2.jpg', FALSE),
  (17, 9, '/images/products/beans-kintamani-1.jpg', TRUE),
  (18, 9, '/images/products/beans-kintamani-2.jpg', FALSE),
  (19, 10, '/images/products/beans-toraja-1.jpg', TRUE),
  (20, 10, '/images/products/beans-toraja-2.jpg', FALSE),
  (21, 11, '/images/products/beans-mandheling-1.jpg', TRUE),
  (22, 11, '/images/products/beans-mandheling-2.jpg', FALSE),
  (23, 12, '/images/products/beans-java-1.jpg', TRUE),
  (24, 12, '/images/products/beans-java-2.jpg', FALSE),
  (25, 13, '/images/products/beans-flores-1.jpg', TRUE),
  (26, 13, '/images/products/beans-flores-2.jpg', FALSE),
  (27, 14, '/images/products/beans-sidikalang-1.jpg', TRUE),
  (28, 14, '/images/products/beans-sidikalang-2.jpg', FALSE),
  (29, 15, '/images/products/beans-lampung-1.jpg', TRUE),
  (30, 15, '/images/products/beans-lampung-2.jpg', FALSE),
  (31, 16, '/images/products/beans-colombia-1.jpg', TRUE),
  (32, 16, '/images/products/beans-colombia-2.jpg', FALSE)
ON DUPLICATE KEY UPDATE
  `product_id` = VALUES(`product_id`),
  `image_url`  = VALUES(`image_url`),
  `is_primary` = VALUES(`is_primary`),
  `updated_at` = CURRENT_TIMESTAMP;
